import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  async redirects() {
    return [
      {
        source: "/how-care-starts/book-a-consultation/",
        destination: "/contact/",
        permanent: true,
      },
      {
        source: "/how-care-starts/first-week-of-care/",
        destination: "/how-care-starts/care-begins/",
        permanent: true,
      },
      {
        source: "/how-care-starts/caregiver-matching/",
        destination: "/how-care-starts/matching-caregivers/",
        permanent: true,
      },
      {
        source: "/how-care-starts/pricing-funding/",
        destination: "/how-care-starts/pricing-and-funding/",
        permanent: true,
      },
      {
        source: "/resources/family-caregiving-guides/",
        destination: "/resources/family-caregiver-support/",
        permanent: true,
      },
      {
        source: "/resources/family-caregiving-guides/caring-for-your-loved-one/",
        destination: "/resources/family-caregiver-support/",
        permanent: true,
      },
      {
        source: "/resources/hospital-discharge-guides/transitioning-home-from-hospital/",
        destination: "/resources/navigating-home-care/",
        permanent: true,
      },
      {
        source: "/resources/family-caregiver-support/caregiver-burnout-warning-signs/",
        destination: "/conditions/caregiver-burnout-support/",
        permanent: true,
      },
      {
        source: "/resources/navigating-home-care/when-a-parent-resists-home-care/",
        destination: "/resources/navigating-home-care/",
        permanent: true,
      },
      {
        source: "/locations/toronto/north-york/",
        destination: "/locations/toronto/north-york-home-care/",
        permanent: true,
      },
      {
        source: "/locations/toronto/scarborough/",
        destination: "/locations/toronto/scarborough-home-care/",
        permanent: true,
      },
      {
        source: "/locations/toronto/etobicoke/",
        destination: "/locations/toronto/etobicoke-home-care/",
        permanent: true,
      },
      {
        source: "/locations/york-region/markham/",
        destination: "/locations/york-region/markham-home-care/",
        permanent: true,
      },
      {
        source: "/locations/york-region/richmond-hill/",
        destination: "/locations/york-region/richmond-hill-home-care/",
        permanent: true,
      },
      {
        source: "/locations/peel-region/mississauga/",
        destination: "/locations/peel-region/mississauga-home-care/",
        permanent: true,
      },
      {
        source: "/conditions/alzheimers-care/",
        destination: "/conditions/dementia-care-at-home/",
        permanent: true,
      },
      {
        source: "/for-professionals/",
        destination: "/healthcare-professionals/",
        permanent: true,
      },
      {
        source: "/our-caregivers/",
        destination: "/",
        permanent: true,
      },
      { source: "/home/", destination: "/", permanent: true, },
      { source: "/our-caregivers", destination: "/", permanent: true, },
      { source: "/home", destination: "/", permanent: true, },
      { source: "/about-us/", destination: "/about/", permanent: true, },
      { source: "/our-caregivers/", destination: "/", permanent: true, },
      { source: "/blog/", destination: "/", permanent: true, },
      { source: "/careers/personal-support-worker", destination: "/", permanent: true, },
      { source: "/about-us", destination: "/about/", permanent: true, },
      { source: "/our-services/decluttering-for-downsizing/", destination: "/", permanent: true, }, { source: "/Pages/mobile/blog/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/our-services/light-housekeeping/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/successfully-navigating-a-hospital-discharge-a-comprehensive-guide-by-arcadia-home-care/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/evaluating-your-parents-care-needs-a-comprehensive-checklist/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/careers/rehabilitation-support-worker/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/our-services/alzheimers-related-dementia-home-care/", destination: "/", permanent: true, },
      { source: "/blog", destination: "/", permanent: true, },
      { source: "/Pages/mobile/our-caregivers/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/our-services/case-management/", destination: "/", permanent: true, },
      { source: "/saying-goodbye-navigating-the-complex-emotions-of-losing-aging-parents", destination: "/", permanent: true, },
      { source: "/site/866b454d/home", destination: "/", permanent: true, },
      { source: "/resources/navigating-home-care/questions-before-hiring-home-care/", destination: "/", permanent: true, },
      { source: "/our-services/alzheimers-related-dementia-home-care", destination: "/", permanent: true, },
      { source: "/careers/rehabilitation-support-worker", destination: "/", permanent: true, },
      { source: "/successfully-navigating-a-hospital-discharge-a-comprehensive-guide-by-arcadia-home-care", destination: "/", permanent: true, },
      { source: "/in-home-care-vs-facility-care-making-the-right-choice-for-your-aging-parents", destination: "/", permanent: true, },
      { source: "/Pages/mobile/careers/", destination: "/", permanent: true, },
      { source: "/evaluating-your-parents-care-needs-a-comprehensive-checklist", destination: "/", permanent: true, },
      { source: "/our-services/decluttering-for-downsizing", destination: "/", permanent: true, },
      { source: "/Pages/mobile/careers/personal-support-worker/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/our-services/decluttering-for-downsizing/", destination: "/", permanent: true, },
      { source: "/Pages/mobile/home/", destination: "/", permanent: true, },
      { source: "/our-approach", destination: "/", permanent: true, },
      { source: "/location-map-old", destination: "/", permanent: true, },
      { source: "/runtime-service-worker.js", destination: "/", permanent: true, },
      { source: "/blog/psw-responsibilities-explained", destination: "/", permanent: true, },
      { source: "/acquired-brain-injury-home-care/", destination: "/", permanent: true, },
      { source: "/location/newmarket/", destination: "/", permanent: true, },
      { source: "/category/cognitive-decline/", destination: "/", permanent: true, },
      { source: "/location/st-catharines", destination: "/", permanent: true, },
      { source: "/understanding-the-pricing-and-value-of-in-home-care-services/", destination: "/", permanent: true, }, { source: "/personal-support-worker", destination: "/", permanent: true, },
      { source: "/understanding-their-struggles-how-aging-parents-feel-during-role-reversal", destination: "/", permanent: true, },
      { source: "/location/markham/", destination: "/", permanent: true, },
      { source: "/location/mississauga", destination: "/", permanent: true, },
      { source: "/location/london/", destination: "/", permanent: true, },
      { source: "/category/planning/", destination: "/", permanent: true, },
      { source: "/avoid-trial-and-error-approach-when-hiring-home-care-agency", destination: "/", permanent: true, },
      { source: "/location/brampton/", destination: "/", permanent: true, },
      { source: "/why-someone-needs-to-play-the-bad-cop/", destination: "/", permanent: true, },
      { source: "/understanding-anxietys-impact-on-cognitive-functioning-and-dementia-in-older-adults", destination: "/", permanent: true, },
      { source: "/location/guelph", destination: "/", permanent: true, },
      { source: "/legal-eagles-seeking-legal-advice-for-aging-parents-care", destination: "/", permanent: true, },
      { source: "/location/oakville", destination: "/", permanent: true, },
      { source: "/how-to-talk-to-elderly-parents-about-home-care", destination: "/", permanent: true, },
      { source: "/from-caring-to-controlling-avoiding-the-pitfalls-when-dealing-with-aging-parents", destination: "/", permanent: true, },
      { source: "/location/sudbury", destination: "/", permanent: true, },
      { source: "/location/kitchener", destination: "/", permanent: true, },
      { source: "/why-someone-needs-to-play-the-bad-cop", destination: "/", permanent: true, },
      { source: "/in-home-care-vs-facility-care--making-the-right-choice-for-your-aging-parents/", destination: "/", permanent: true, },
      { source: "/how-to-help-your-parents-remain-socially-active/", destination: "/", permanent: true, },
      { source: "/the-unspoken-grief-dealing-with-the-decline-of-aging-parents/", destination: "/", permanent: true, },
      { source: "/palliative-home-care/", destination: "/", permanent: true, },
      { source: "/location/brampton", destination: "/", permanent: true, },
      { source: "/from-guilt-to-understanding-managing-negative-emotions-in-role-reversal", destination: "/", permanent: true, },
      { source: "/unlocking-the-future-of-alzheimers-care-transforming-dementia-treatment-for-the-next-generation/", destination: "/", permanent: true, },
      { source: "/location/barrie", destination: "/", permanent: true, },
      { source: "/alzheimers-related-dementia-home-care/", destination: "/", permanent: true, },
      { source: "/location/thunder-bay", destination: "/", permanent: true, },
      { source: "/download-ebook/", destination: "/", permanent: true, },
      { source: "/family-ties-managing-conflict-when-caring-for-aging-parents", destination: "/", permanent: true, },
      { source: "/location/kitchener/", destination: "/", permanent: true, }, { source: "/location/markham", destination: "/", permanent: true, },
      { source: "/blog/integrating-home-care-into-financial-planning-ontario-advisors", destination: "/", permanent: true, },
      { source: "/wp-content/uploads/2023/07/Referral-Form-4-1.pdf", destination: "/", permanent: true, },
      { source: "/our-services/acquire-brain-injury-home-care", destination: "/", permanent: true, },
      { source: "/location/hamilton", destination: "/", permanent: true, },
      { source: "/location/oshawa", destination: "/", permanent: true, }, { source: "/the-emotional-journey-understanding-the-impact-of-grief-and-loss-when-caring-for-aging-parents", destination: "/", permanent: true, },
      { source: "/understanding-the-pricing-and-value-of-in-home-care-services", destination: "/", permanent: true, }, { source: "/blog/expert-rehabilitation-support", destination: "/", permanent: true, },
      { source: "/blog/personalized-palliative-care-at-home", destination: "/", permanent: true, },
      { source: "/location/", destination: "/", permanent: true, },
      { source: "/site/866b454d/training", destination: "/", permanent: true, },
      { source: "/blog/benefits-arcadia-home-care-alzheimers-dementia", destination: "/", permanent: true, },
      { source: "/blog/page/5/", destination: "/", permanent: true, },
      { source: "/legal-eagles-seeking-legal-advice-for-aging-parents-care/", destination: "/", permanent: true, },
      { source: "/location/toronto", destination: "/", permanent: true, },
      { source: "/comments/feed/", destination: "/", permanent: true, }, { source: "/evaluating-your-parents--care-needs--a-comprehensive-checklist/", destination: "/", permanent: true, },
      { source: "/rehabilitation-support-worker/", destination: "/", permanent: true, },
      { source: "/training", destination: "/", permanent: true, },
      { source: "/successfully-navigating-a-hospital-discharge--a-comprehensive-guide-by-arcadia-home-care/", destination: "/", permanent: true, },
      { source: "/how-to-manage-difficult-situations-in-aging-parents--a-4-step-guide/", destination: "/", permanent: true, },
      { source: "/case-management/", destination: "/", permanent: true, },
      { source: "/how-to-talk-to-elderly-parents-about-home-care/", destination: "/", permanent: true, },
      { source: "/decluttering-for-downsizing/", destination: "/", permanent: true, },
      { source: "/family-funded-home-care/", destination: "/", permanent: true, },
      { source: "/rehabilitation-support/", destination: "/", permanent: true, },
      { source: "/blog/arcadia-palliative-care-benefits", destination: "/", permanent: true, },
      { source: "/psw-application/", destination: "/", permanent: true, },
      { source: "/light-housekeeping/", destination: "/", permanent: true, },
      { source: "/blog/compassionate-care-acquired-brain-injury", destination: "/", permanent: true, },
    ];
  },
};

export default nextConfig;